# Generated by Django 3.2.13 on 2022-05-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicee', models.CharField(max_length=100)),
                ('sdescribe', models.CharField(max_length=100)),
                ('sprice', models.CharField(max_length=100)),
                ('sduration', models.CharField(max_length=100)),
                ('mcharges', models.CharField(max_length=100)),
            ],
        ),
    ]
