# Generated by Django 3.2.13 on 2022-05-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0005_rename_servicee_addservices_servicet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addservices',
            old_name='servicet',
            new_name='stitle',
        ),
    ]
