# Generated by Django 3.2.13 on 2022-05-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0008_contact2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact2',
            new_name='Contact1',
        ),
    ]
