# Generated by Django 3.2.13 on 2022-05-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0009_rename_contact2_contact1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfeedback1',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Addservices1',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('stitle', models.CharField(max_length=100)),
                ('sdescribe', models.CharField(max_length=100)),
                ('sprice', models.CharField(max_length=100)),
                ('sduration', models.CharField(max_length=100)),
                ('mcharges', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback1',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register1',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
            ],
        ),
    ]
