# Generated by Django 3.2.13 on 2022-05-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0010_addfeedback1_addservices1_feedback1_register1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addfeedback',
        ),
        migrations.DeleteModel(
            name='AddServices',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
