# Generated by Django 3.2.13 on 2022-05-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0011_auto_20220519_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register1',
            new_name='Register',
        ),
    ]
