# Generated by Django 3.2.13 on 2022-05-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0012_rename_register1_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact1',
            new_name='Contact',
        ),
    ]
