# Generated by Django 3.2.13 on 2022-05-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0013_rename_contact1_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback1',
            new_name='Feedback',
        ),
    ]
