# Generated by Django 3.2.13 on 2022-05-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0014_rename_feedback1_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addservices1',
            new_name='Addservice',
        ),
    ]
