# Generated by Django 3.2.13 on 2022-05-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0015_rename_addservices1_addservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addfeedback1',
            new_name='Addfeedback',
        ),
    ]
