# Generated by Django 3.2.13 on 2022-06-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapplication', '0016_rename_addfeedback1_addfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default=1, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
